Adding docker build push step in automated tests jobs for loading cached images

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -104,91 +104,119 @@ jobs:
           cache-from: type=gha,scope=${{ matrix.image_name }}
           cache-to: type=gha,mode=max,scope=${{ matrix.image_name }}
 
-  # run-automated-tests:
-  #   needs: [docker-build-and-cache-images]
-  #   runs-on: ubuntu-latest
+  run-automated-tests:
+    needs: [docker-build-and-cache-images]
+    runs-on: ubuntu-latest
 
-  #   permissions:
-  #     contents: read
-  #     packages: write
+    permissions:
+      contents: read
+      packages: write
 
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-  #     - name: Ensure Docker image version is not referencing an existing release
-  #       id: docker-image-version-check
-  #       shell: bash
-  #       run: |
-  #         if ! [[ -s '.env'  ]]; then
-  #           echo 'Error: No .env file found.'
-  #           exit 1
-  #         fi
+      - name: Ensure Docker image version is not referencing an existing release
+        id: docker-image-version-check
+        shell: bash
+        run: |
+          if ! [[ -s '.env'  ]]; then
+            echo 'Error: No .env file found.'
+            exit 1
+          fi
 
-  #         if ! grep -qE '^TAG=' .env; then
-  #           echo 'Error: .env must contain a TAG variable.'
-  #           exit 1
-  #         fi
+          if ! grep -qE '^TAG=' .env; then
+            echo 'Error: .env must contain a TAG variable.'
+            exit 1
+          fi
 
-  #         source .env
+          source .env
 
-  #         # Fail if any previous Docker image version value matches the one in
-  #         # this PR (excluding the current image version).
-  #         for commit in $(git --no-pager log --first-parent --format=%H -- .env | tail -n +2); do
-  #           if git --no-pager grep -hF "${TAG}" $commit -- .env | grep -qx ${TAG}; then
-  #             echo 'Error: The version in .env matches an'
-  #             echo '       earlier version on main. Please update the value in'
-  #             echo '       .env to a new version.'
-  #             exit 1
-  #           fi
-  #         done
+          # Fail if any previous Docker image version value matches the one in
+          # this PR (excluding the current image version).
+          for commit in $(git --no-pager log --first-parent --format=%H -- .env | tail -n +2); do
+            if git --no-pager grep -hF "${TAG}" $commit -- .env | grep -qx ${TAG}; then
+              echo 'Error: The version in .env matches an'
+              echo '       earlier version on main. Please update the value in'
+              echo '       .env to a new version.'
+              exit 1
+            fi
+          done
 
-  #         if git show-ref --tags --verify --quiet "refs/tags/v${TAG}"; then
-  #           echo "Error: The tag 'v${TAG}' is already a GitHub release."
-  #           echo '       Please update the version in .env'
-  #           exit 1
-  #         else
-  #           echo "TAG=${TAG}" >> "${GITHUB_OUTPUT}"
-  #         fi
+          if git show-ref --tags --verify --quiet "refs/tags/v${TAG}"; then
+            echo "Error: The tag 'v${TAG}' is already a GitHub release."
+            echo '       Please update the version in .env'
+            exit 1
+          else
+            echo "TAG=${TAG}" >> "${GITHUB_OUTPUT}"
+          fi
 
-  #     - name: Set up QEMU
-  #       uses: docker/setup-qemu-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-  #     - name: Set Docker image metadata
-  #       id: meta
-  #       uses: docker/metadata-action@v5
-  #       with:
-  #         images: ghcr.io/everest/everest-demo/manager
-  #         tags: |
-  #           type=semver,pattern={{version}},value=v${{ steps.docker-image-version-check.outputs.TAG }}
+      - name: Set Docker mqtt-server image metadata
+        id: meta_mqtt
+        uses: docker/metadata-action@v5
+        with:
+          images: ghcr.io/everest/everest-demo/mqtt-server
+          tags: |
+            type=semver,pattern={{version}},value=v${{ steps.docker-image-version-check.outputs.TAG }}
 
-  #     - name: Log into GitHub container registry
-  #       if: github.event_name != 'pull_request'
-  #       uses: docker/login-action@v3
-  #       with:
-  #         registry: ghcr.io
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set Docker manager image metadata
+        id: meta_manager
+        uses: docker/metadata-action@v5
+        with:
+          images: ghcr.io/everest/everest-demo/manager
+          tags: |
+            type=semver,pattern={{version}},value=v${{ steps.docker-image-version-check.outputs.TAG }}
 
-  #     - name: Run automated tests using docker-compose.automated-tests.yml 
-  #       run: |
-  #         echo "Running docker compose up..."
-  #         docker compose --project-name everest-ac-demo \
-  #                 --file "docker-compose.automated-tests.yml" up \
-  #                   --abort-on-container-exit \
-  #                   --exit-code-from manager
+      - name: Log into GitHub container registry
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-  #         exit_code=$?            
-  #         echo "Docker-compose up exit code from manager service: $exit_code"
+      - name: Import mqtt-server from GitHub Actions Cache to Docker
+        uses: docker/build-push-action@v6
+        with:
+          load: true
+          push: false
+          tags: ${{ steps.meta_mqtt.outputs.tags }}
+          labels: ${{ steps.meta_mqtt.outputs.labels }}
+          cache-from: type=gha,scope=mqtt-server
+          cache-to: type=gha,mode=max,scope=mqtt-server
+
+      - name: Import manager from GitHub Actions Cache to Docker
+        uses: docker/build-push-action@v6
+        with:
+          load: true
+          push: false
+          tags: ${{ steps.meta_manager.outputs.tags }}
+          labels: ${{ steps.meta_manager.outputs.labels }}
+          cache-from: type=gha,scope=manager
+          cache-to: type=gha,mode=max,scope=manager
+
+      - name: Run automated tests using docker-compose.automated-tests.yml 
+        run: |
+          echo "Running docker compose up..."
+          docker compose --project-name everest-ac-demo \
+                  --file "docker-compose.automated-tests.yml" up \
+                    --abort-on-container-exit \
+                    --exit-code-from manager
+
+          exit_code=$?            
+          echo "Docker-compose up exit code from manager service: $exit_code"
 
   docker-build-and-push-images:
-    # needs: [run-automated-tests]
-    needs: [docker-build-and-cache-images]
+    needs: [run-automated-tests]
+    # needs: [docker-build-and-cache-images]
     runs-on: ubuntu-latest
 
     permissions:
